# Generated by Django 5.0 on 2023-12-18 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice_board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='weeks',
            field=models.IntegerField(default=1, help_text='Weeks'),
            preserve_default=False,
        ),
    ]
