# Generated by Django 5.0 on 2023-12-18 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice_board', '0002_week_weeks'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='weeks',
            field=models.IntegerField(default=1, help_text='Weeks'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignment',
            name='week_id',
            field=models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='notice_board.week'),
        ),
    ]
