# Generated by Django 5.0 on 2023-12-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice_board', '0003_assignment_weeks_alter_assignment_week_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
