# Generated by Django 5.0 on 2023-12-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice_board', '0005_remove_notice_student_id_notice_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='student_id',
            field=models.IntegerField(default=1, help_text='Student ID', unique=True),
            preserve_default=False,
        ),
    ]
