# Generated by Django 5.0 on 2023-12-18 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice_board', '0006_notice_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='week',
            name='student_id',
        ),
        migrations.AddField(
            model_name='week',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='notice_board.user'),
            preserve_default=False,
        ),
    ]
