# Generated by Django 5.0 on 2023-12-18 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice_board', '0007_remove_week_student_id_week_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='week_id',
            field=models.ForeignKey(db_column='week_id', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='notice_board.week'),
        ),
    ]
