# Generated by Django 5.0 on 2023-12-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice_board', '0008_alter_assignment_week_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='student_id',
            field=models.IntegerField(default=1, help_text='Student ID'),
            preserve_default=False,
        ),
    ]
