# Generated by Django 5.0 on 2023-12-19 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice_board', '0009_assignment_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='weeks',
            field=models.IntegerField(help_text='Weeks', unique=True),
        ),
    ]
