# Generated by Django 5.0 on 2023-12-19 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice_board', '0010_alter_week_weeks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='weeks',
            field=models.IntegerField(help_text='Weeks'),
        ),
    ]
