# Generated by Django 5.0 on 2023-12-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice_board', '0012_remove_notice_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='submission_status',
        ),
        migrations.AddField(
            model_name='week',
            name='submission_status',
            field=models.CharField(choices=[('T', 'Submitted'), ('F', 'Not Submitted'), ('L', 'Late')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
