# Generated by Django 5.0 on 2023-12-20 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice_board', '0013_remove_assignment_submission_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='assignment_title',
        ),
        migrations.AddField(
            model_name='week',
            name='assignment_title',
            field=models.CharField(default=1, help_text='assignment_title', max_length=100),
            preserve_default=False,
        ),
    ]
