# Generated by Django 5.0 on 2023-12-23 12:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice_board', '0014_remove_assignment_assignment_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='deadline',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignment',
            name='submission_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='notice',
            name='notice_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
