# Generated by Django 5.0 on 2023-12-23 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice_board', '0016_alter_week_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='week',
            name='deadline',
        ),
    ]
