# Generated by Django 5.0 on 2023-12-23 12:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice_board', '0017_remove_week_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='deadline',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
