# Generated by Django 5.0 on 2023-12-23 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice_board', '0018_week_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='assignment_type',
            field=models.CharField(choices=[('C', 'Common'), ('F', 'Frontend'), ('B', 'Backend')], default='C', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='division',
            field=models.CharField(help_text='front or back or admin(front admin or back admin)', max_length=100),
        ),
    ]
