# Generated by Django 5.0 on 2023-12-24 07:59

import django.core.validators
import notice_board.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice_board', '0019_week_assignment_type_alter_user_division'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='file',
            field=models.FileField(upload_to=notice_board.models.upload_to_assignments, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'hwp'])]),
        ),
    ]
