# Generated by Django 5.0 on 2023-12-24 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice_board', '0020_alter_assignment_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='notice/'),
        ),
    ]
